# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #


default_platform(:android)

platform :android do
  desc "Build and upload Android App Bundle to Google Play Internal Testing"
  lane :playstore do
    gradle(
      task: "clean"
    )

    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      skip_upload_apk: true,
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )

  # desc "Build and upload Android App Bundle to Google Play Production"
  # lane :playstore_production do
  #   gradle(
  #     task: "clean"
  #   )

  #   gradle(
  #     task: "bundle",
  #     build_type: "Release"
  #   )

  #   upload_to_play_store(
  #     track: "production",         # <-- production track
  #     release_status: "completed", # <-- auto publish
  #     skip_upload_apk: true,
  #     skip_upload_metadata: false,
  #     skip_upload_images: false,
  #     skip_upload_screenshots: false
  #   )
    
  end
end


